---
version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    kubernetes:
      patterns:
      - k8s.io/api
      - k8s.io/apimachinery
      - k8s.io/client-go

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
