version: "2"
run:
  go: "1.25"
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - kubeapilinter
  settings:
    custom:
      kubeapilinter:
        type: module
        description: KAL is the Kube-API-Linter and lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            enable:
              - "commentstart"
              - "conditions"
              - "conflictingmarkers"
              - "duplicatemarkers"
              - "forbiddenmarkers"
              - "integers"
              - "jsontags"
              - "maxlength"
              - "nobools"
              - "nodurations"
              - "nofloats"
              - "nomaps"
              - "nonullable"
              - "notimestamp"
              - "optionalfields"
              - "optionalorrequired"
              - "requiredfields"
              - "ssatags"
              - "statusoptional"
              - "statussubresource"
              - "uniquemarkers"
            disable:
              - "*"
          lintersConfig:
            conflictingmarkers:
              conflicts:
                - name: "default_vs_required"
                  sets:
                    - ["default", "kubebuilder:default"]
                    - ["required", "kubebuilder:validation:Required", "k8s:required"]
                  description: "A field with a default value cannot be required"
            forbiddenmarkers:
              markers:
                - identifier: "kubebuilder:default"
                - identifier: "default"
            conditions:
              isFirstField: Warn
              usePatchStrategy: Forbid
              useProtobuf: Forbid
            optionalfields:
              pointers:
                preference: WhenRequired
                policy: SuggestFix
              omitempty:
                policy: SuggestFix
  exclusions:
    generated: strict
    paths:
      - zz_generated.*\.go$
      - ".*_test.go"
    rules:
      - path-except: "^api//*"
        linters:
          - kubeapilinter
      - path: "api/v1alpha1"
        linters:
          - kubeapilinter
      - path: "api/v1alpha2"
        text: "nobools"
        linters:
          - kubeapilinter
      - path: "api/v1alpha2"
        text: "does not need to be a pointer"
        linters:
          - kubeapilinter
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
