# permissions for end users to view proxmoxmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: proxmoxmachine-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-proxmox
    app.kubernetes.io/part-of: cluster-api-provider-proxmox
    app.kubernetes.io/managed-by: kustomize
  name: proxmoxmachine-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - proxmoxmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - proxmoxmachines/status
  verbs:
  - get
