//go:build !ignore_autogenerated_core_v1alpha1
// +build !ignore_autogenerated_core_v1alpha1

/*
Copyright 2023 IONOS Cloud.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha2 "github.com/ionos-cloud/cluster-api-provider-proxmox/api/v1alpha2"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AdditionalNetworkDevice)(nil), (*v1alpha2.AdditionalNetworkDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdditionalNetworkDevice_To_v1alpha2_AdditionalNetworkDevice(a.(*AdditionalNetworkDevice), b.(*v1alpha2.AdditionalNetworkDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.AdditionalNetworkDevice)(nil), (*AdditionalNetworkDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AdditionalNetworkDevice_To_v1alpha1_AdditionalNetworkDevice(a.(*v1alpha2.AdditionalNetworkDevice), b.(*AdditionalNetworkDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiskSize)(nil), (*v1alpha2.DiskSize)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(a.(*DiskSize), b.(*v1alpha2.DiskSize), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.DiskSize)(nil), (*DiskSize)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(a.(*v1alpha2.DiskSize), b.(*DiskSize), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPAddress)(nil), (*v1alpha2.IPAddress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPAddress_To_v1alpha2_IPAddress(a.(*IPAddress), b.(*v1alpha2.IPAddress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.IPAddress)(nil), (*IPAddress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_IPAddress_To_v1alpha1_IPAddress(a.(*v1alpha2.IPAddress), b.(*IPAddress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPConfig)(nil), (*v1alpha2.IPConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPConfig_To_v1alpha2_IPConfig(a.(*IPConfig), b.(*v1alpha2.IPConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkDevice)(nil), (*v1alpha2.NetworkDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(a.(*NetworkDevice), b.(*v1alpha2.NetworkDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkSpec)(nil), (*v1alpha2.NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(a.(*NetworkSpec), b.(*v1alpha2.NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NetworkSpec)(nil), (*NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(a.(*v1alpha2.NetworkSpec), b.(*NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkStatus)(nil), (*v1alpha2.NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(a.(*NetworkStatus), b.(*v1alpha2.NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NetworkStatus)(nil), (*NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(a.(*v1alpha2.NetworkStatus), b.(*NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeLocation)(nil), (*v1alpha2.NodeLocation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(a.(*NodeLocation), b.(*v1alpha2.NodeLocation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NodeLocation)(nil), (*NodeLocation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(a.(*v1alpha2.NodeLocation), b.(*NodeLocation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeLocations)(nil), (*v1alpha2.NodeLocations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(a.(*NodeLocations), b.(*v1alpha2.NodeLocations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NodeLocations)(nil), (*NodeLocations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(a.(*v1alpha2.NodeLocations), b.(*NodeLocations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxCluster)(nil), (*v1alpha2.ProxmoxCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(a.(*ProxmoxCluster), b.(*v1alpha2.ProxmoxCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxCluster)(nil), (*ProxmoxCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(a.(*v1alpha2.ProxmoxCluster), b.(*ProxmoxCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterList)(nil), (*v1alpha2.ProxmoxClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(a.(*ProxmoxClusterList), b.(*v1alpha2.ProxmoxClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterList)(nil), (*ProxmoxClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(a.(*v1alpha2.ProxmoxClusterList), b.(*ProxmoxClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterSpec)(nil), (*v1alpha2.ProxmoxClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(a.(*ProxmoxClusterSpec), b.(*v1alpha2.ProxmoxClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterSpec)(nil), (*ProxmoxClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(a.(*v1alpha2.ProxmoxClusterSpec), b.(*ProxmoxClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterStatus)(nil), (*v1alpha2.ProxmoxClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(a.(*ProxmoxClusterStatus), b.(*v1alpha2.ProxmoxClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterStatus)(nil), (*ProxmoxClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(a.(*v1alpha2.ProxmoxClusterStatus), b.(*ProxmoxClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachine)(nil), (*v1alpha2.ProxmoxMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(a.(*ProxmoxMachine), b.(*v1alpha2.ProxmoxMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachine)(nil), (*ProxmoxMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(a.(*v1alpha2.ProxmoxMachine), b.(*ProxmoxMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineList)(nil), (*v1alpha2.ProxmoxMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(a.(*ProxmoxMachineList), b.(*v1alpha2.ProxmoxMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineList)(nil), (*ProxmoxMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(a.(*v1alpha2.ProxmoxMachineList), b.(*ProxmoxMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineSpec)(nil), (*v1alpha2.ProxmoxMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(a.(*ProxmoxMachineSpec), b.(*v1alpha2.ProxmoxMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineSpec)(nil), (*ProxmoxMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(a.(*v1alpha2.ProxmoxMachineSpec), b.(*ProxmoxMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineStatus)(nil), (*v1alpha2.ProxmoxMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(a.(*ProxmoxMachineStatus), b.(*v1alpha2.ProxmoxMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineStatus)(nil), (*ProxmoxMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(a.(*v1alpha2.ProxmoxMachineStatus), b.(*ProxmoxMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineTemplate)(nil), (*v1alpha2.ProxmoxMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(a.(*ProxmoxMachineTemplate), b.(*v1alpha2.ProxmoxMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineTemplate)(nil), (*ProxmoxMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(a.(*v1alpha2.ProxmoxMachineTemplate), b.(*ProxmoxMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineTemplateList)(nil), (*v1alpha2.ProxmoxMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(a.(*ProxmoxMachineTemplateList), b.(*v1alpha2.ProxmoxMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineTemplateList)(nil), (*ProxmoxMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(a.(*v1alpha2.ProxmoxMachineTemplateList), b.(*ProxmoxMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineTemplateResource)(nil), (*v1alpha2.ProxmoxMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(a.(*ProxmoxMachineTemplateResource), b.(*v1alpha2.ProxmoxMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineTemplateResource)(nil), (*ProxmoxMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(a.(*v1alpha2.ProxmoxMachineTemplateResource), b.(*ProxmoxMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineTemplateSpec)(nil), (*v1alpha2.ProxmoxMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(a.(*ProxmoxMachineTemplateSpec), b.(*v1alpha2.ProxmoxMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineTemplateSpec)(nil), (*ProxmoxMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(a.(*v1alpha2.ProxmoxMachineTemplateSpec), b.(*ProxmoxMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Storage)(nil), (*v1alpha2.Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Storage_To_v1alpha2_Storage(a.(*Storage), b.(*v1alpha2.Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Storage)(nil), (*Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Storage_To_v1alpha1_Storage(a.(*v1alpha2.Storage), b.(*Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachine)(nil), (*v1alpha2.VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(a.(*VirtualMachine), b.(*v1alpha2.VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VirtualMachine)(nil), (*VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(a.(*v1alpha2.VirtualMachine), b.(*VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineCloneSpec)(nil), (*v1alpha2.VirtualMachineCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(a.(*VirtualMachineCloneSpec), b.(*v1alpha2.VirtualMachineCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VirtualMachineCloneSpec)(nil), (*VirtualMachineCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(a.(*v1alpha2.VirtualMachineCloneSpec), b.(*VirtualMachineCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*NetworkConfig)(nil), (*v1alpha2.NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkConfig_To_v1alpha2_NetworkConfig(a.(*NetworkConfig), b.(*v1alpha2.NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.IPConfig)(nil), (*IPConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_IPConfig_To_v1alpha1_IPConfig(a.(*v1alpha2.IPConfig), b.(*IPConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.NetworkConfig)(nil), (*NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkConfig_To_v1alpha1_NetworkConfig(a.(*v1alpha2.NetworkConfig), b.(*NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.NetworkDevice)(nil), (*NetworkDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice(a.(*v1alpha2.NetworkDevice), b.(*NetworkDevice), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AdditionalNetworkDevice_To_v1alpha2_AdditionalNetworkDevice(in *AdditionalNetworkDevice, out *v1alpha2.AdditionalNetworkDevice, s conversion.Scope) error {
	if err := Convert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(&in.NetworkDevice, &out.NetworkDevice, s); err != nil {
		return err
	}
	out.Name = in.Name
	out.IPv4PoolRef = (*v1.TypedLocalObjectReference)(unsafe.Pointer(in.IPv4PoolRef))
	out.IPv6PoolRef = (*v1.TypedLocalObjectReference)(unsafe.Pointer(in.IPv6PoolRef))
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	return nil
}

// Convert_v1alpha1_AdditionalNetworkDevice_To_v1alpha2_AdditionalNetworkDevice is an autogenerated conversion function.
func Convert_v1alpha1_AdditionalNetworkDevice_To_v1alpha2_AdditionalNetworkDevice(in *AdditionalNetworkDevice, out *v1alpha2.AdditionalNetworkDevice, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdditionalNetworkDevice_To_v1alpha2_AdditionalNetworkDevice(in, out, s)
}

func autoConvert_v1alpha2_AdditionalNetworkDevice_To_v1alpha1_AdditionalNetworkDevice(in *v1alpha2.AdditionalNetworkDevice, out *AdditionalNetworkDevice, s conversion.Scope) error {
	if err := Convert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice(&in.NetworkDevice, &out.NetworkDevice, s); err != nil {
		return err
	}
	out.Name = in.Name
	out.IPv4PoolRef = (*v1.TypedLocalObjectReference)(unsafe.Pointer(in.IPv4PoolRef))
	out.IPv6PoolRef = (*v1.TypedLocalObjectReference)(unsafe.Pointer(in.IPv6PoolRef))
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	return nil
}

// Convert_v1alpha2_AdditionalNetworkDevice_To_v1alpha1_AdditionalNetworkDevice is an autogenerated conversion function.
func Convert_v1alpha2_AdditionalNetworkDevice_To_v1alpha1_AdditionalNetworkDevice(in *v1alpha2.AdditionalNetworkDevice, out *AdditionalNetworkDevice, s conversion.Scope) error {
	return autoConvert_v1alpha2_AdditionalNetworkDevice_To_v1alpha1_AdditionalNetworkDevice(in, out, s)
}

func autoConvert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(in *DiskSize, out *v1alpha2.DiskSize, s conversion.Scope) error {
	out.Disk = in.Disk
	out.SizeGB = in.SizeGB
	return nil
}

// Convert_v1alpha1_DiskSize_To_v1alpha2_DiskSize is an autogenerated conversion function.
func Convert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(in *DiskSize, out *v1alpha2.DiskSize, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(in, out, s)
}

func autoConvert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(in *v1alpha2.DiskSize, out *DiskSize, s conversion.Scope) error {
	out.Disk = in.Disk
	out.SizeGB = in.SizeGB
	return nil
}

// Convert_v1alpha2_DiskSize_To_v1alpha1_DiskSize is an autogenerated conversion function.
func Convert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(in *v1alpha2.DiskSize, out *DiskSize, s conversion.Scope) error {
	return autoConvert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(in, out, s)
}

func autoConvert_v1alpha1_IPAddress_To_v1alpha2_IPAddress(in *IPAddress, out *v1alpha2.IPAddress, s conversion.Scope) error {
	out.IPV4 = in.IPV4
	out.IPV6 = in.IPV6
	return nil
}

// Convert_v1alpha1_IPAddress_To_v1alpha2_IPAddress is an autogenerated conversion function.
func Convert_v1alpha1_IPAddress_To_v1alpha2_IPAddress(in *IPAddress, out *v1alpha2.IPAddress, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPAddress_To_v1alpha2_IPAddress(in, out, s)
}

func autoConvert_v1alpha2_IPAddress_To_v1alpha1_IPAddress(in *v1alpha2.IPAddress, out *IPAddress, s conversion.Scope) error {
	out.IPV4 = in.IPV4
	out.IPV6 = in.IPV6
	return nil
}

// Convert_v1alpha2_IPAddress_To_v1alpha1_IPAddress is an autogenerated conversion function.
func Convert_v1alpha2_IPAddress_To_v1alpha1_IPAddress(in *v1alpha2.IPAddress, out *IPAddress, s conversion.Scope) error {
	return autoConvert_v1alpha2_IPAddress_To_v1alpha1_IPAddress(in, out, s)
}

func autoConvert_v1alpha1_IPConfig_To_v1alpha2_IPConfig(in *IPConfig, out *v1alpha2.IPConfig, s conversion.Scope) error {
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	out.Prefix = in.Prefix
	out.Gateway = in.Gateway
	return nil
}

// Convert_v1alpha1_IPConfig_To_v1alpha2_IPConfig is an autogenerated conversion function.
func Convert_v1alpha1_IPConfig_To_v1alpha2_IPConfig(in *IPConfig, out *v1alpha2.IPConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPConfig_To_v1alpha2_IPConfig(in, out, s)
}

func autoConvert_v1alpha2_IPConfig_To_v1alpha1_IPConfig(in *v1alpha2.IPConfig, out *IPConfig, s conversion.Scope) error {
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	out.Prefix = in.Prefix
	out.Gateway = in.Gateway
	// WARNING: in.DHCP requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_NetworkConfig_To_v1alpha2_NetworkConfig(in *NetworkConfig, out *v1alpha2.NetworkConfig, s conversion.Scope) error {
	if in.IPv4Config != nil {
		in, out := &in.IPv4Config, &out.IPv4Config
		*out = new(v1alpha2.IPConfig)
		if err := Convert_v1alpha1_IPConfig_To_v1alpha2_IPConfig(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.IPv4Config = nil
	}
	if in.IPv6Config != nil {
		in, out := &in.IPv6Config, &out.IPv6Config
		*out = new(v1alpha2.IPConfig)
		if err := Convert_v1alpha1_IPConfig_To_v1alpha2_IPConfig(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.IPv6Config = nil
	}
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	return nil
}

func autoConvert_v1alpha2_NetworkConfig_To_v1alpha1_NetworkConfig(in *v1alpha2.NetworkConfig, out *NetworkConfig, s conversion.Scope) error {
	if in.IPv4Config != nil {
		in, out := &in.IPv4Config, &out.IPv4Config
		*out = new(IPConfig)
		if err := Convert_v1alpha2_IPConfig_To_v1alpha1_IPConfig(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.IPv4Config = nil
	}
	if in.IPv6Config != nil {
		in, out := &in.IPv6Config, &out.IPv6Config
		*out = new(IPConfig)
		if err := Convert_v1alpha2_IPConfig_To_v1alpha1_IPConfig(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.IPv6Config = nil
	}
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	return nil
}

func autoConvert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(in *NetworkDevice, out *v1alpha2.NetworkDevice, s conversion.Scope) error {
	out.Bridge = in.Bridge
	out.Model = (*string)(unsafe.Pointer(in.Model))
	return nil
}

// Convert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice is an autogenerated conversion function.
func Convert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(in *NetworkDevice, out *v1alpha2.NetworkDevice, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(in, out, s)
}

func autoConvert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice(in *v1alpha2.NetworkDevice, out *NetworkDevice, s conversion.Scope) error {
	out.Bridge = in.Bridge
	out.Model = (*string)(unsafe.Pointer(in.Model))
	// WARNING: in.DHCP4 requires manual conversion: does not exist in peer-type
	// WARNING: in.DHCP6 requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(in *NetworkSpec, out *v1alpha2.NetworkSpec, s conversion.Scope) error {
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(v1alpha2.NetworkDevice)
		if err := Convert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Default = nil
	}
	if in.AdditionalDevices != nil {
		in, out := &in.AdditionalDevices, &out.AdditionalDevices
		*out = make([]v1alpha2.AdditionalNetworkDevice, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_AdditionalNetworkDevice_To_v1alpha2_AdditionalNetworkDevice(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.AdditionalDevices = nil
	}
	return nil
}

// Convert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec is an autogenerated conversion function.
func Convert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(in *NetworkSpec, out *v1alpha2.NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(in, out, s)
}

func autoConvert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(in *v1alpha2.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(NetworkDevice)
		if err := Convert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Default = nil
	}
	if in.AdditionalDevices != nil {
		in, out := &in.AdditionalDevices, &out.AdditionalDevices
		*out = make([]AdditionalNetworkDevice, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_AdditionalNetworkDevice_To_v1alpha1_AdditionalNetworkDevice(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.AdditionalDevices = nil
	}
	return nil
}

// Convert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec is an autogenerated conversion function.
func Convert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(in *v1alpha2.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(in, out, s)
}

func autoConvert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(in *NetworkStatus, out *v1alpha2.NetworkStatus, s conversion.Scope) error {
	out.Connected = in.Connected
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MACAddr = in.MACAddr
	out.NetworkName = in.NetworkName
	return nil
}

// Convert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(in *NetworkStatus, out *v1alpha2.NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(in *v1alpha2.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	out.Connected = in.Connected
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MACAddr = in.MACAddr
	out.NetworkName = in.NetworkName
	return nil
}

// Convert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(in *v1alpha2.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(in *NodeLocation, out *v1alpha2.NodeLocation, s conversion.Scope) error {
	out.Machine = in.Machine
	out.Node = in.Node
	return nil
}

// Convert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation is an autogenerated conversion function.
func Convert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(in *NodeLocation, out *v1alpha2.NodeLocation, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(in, out, s)
}

func autoConvert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(in *v1alpha2.NodeLocation, out *NodeLocation, s conversion.Scope) error {
	out.Machine = in.Machine
	out.Node = in.Node
	return nil
}

// Convert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation is an autogenerated conversion function.
func Convert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(in *v1alpha2.NodeLocation, out *NodeLocation, s conversion.Scope) error {
	return autoConvert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(in, out, s)
}

func autoConvert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(in *NodeLocations, out *v1alpha2.NodeLocations, s conversion.Scope) error {
	out.ControlPlane = *(*[]v1alpha2.NodeLocation)(unsafe.Pointer(&in.ControlPlane))
	out.Workers = *(*[]v1alpha2.NodeLocation)(unsafe.Pointer(&in.Workers))
	return nil
}

// Convert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations is an autogenerated conversion function.
func Convert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(in *NodeLocations, out *v1alpha2.NodeLocations, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(in, out, s)
}

func autoConvert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(in *v1alpha2.NodeLocations, out *NodeLocations, s conversion.Scope) error {
	out.ControlPlane = *(*[]NodeLocation)(unsafe.Pointer(&in.ControlPlane))
	out.Workers = *(*[]NodeLocation)(unsafe.Pointer(&in.Workers))
	return nil
}

// Convert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations is an autogenerated conversion function.
func Convert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(in *v1alpha2.NodeLocations, out *NodeLocations, s conversion.Scope) error {
	return autoConvert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(in *ProxmoxCluster, out *v1alpha2.ProxmoxCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(in *ProxmoxCluster, out *v1alpha2.ProxmoxCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(in *v1alpha2.ProxmoxCluster, out *ProxmoxCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(in *v1alpha2.ProxmoxCluster, out *ProxmoxCluster, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(in *ProxmoxClusterList, out *v1alpha2.ProxmoxClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ProxmoxCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(in *ProxmoxClusterList, out *v1alpha2.ProxmoxClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(in *v1alpha2.ProxmoxClusterList, out *ProxmoxClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(in *v1alpha2.ProxmoxClusterList, out *ProxmoxClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(in *ProxmoxClusterSpec, out *v1alpha2.ProxmoxClusterSpec, s conversion.Scope) error {
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	out.AllowedNodes = *(*[]string)(unsafe.Pointer(&in.AllowedNodes))
	if err := Convert_v1alpha1_NetworkConfig_To_v1alpha2_NetworkConfig(&in.NetworkConfig, &out.NetworkConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(in *ProxmoxClusterSpec, out *v1alpha2.ProxmoxClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(in *v1alpha2.ProxmoxClusterSpec, out *ProxmoxClusterSpec, s conversion.Scope) error {
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	out.AllowedNodes = *(*[]string)(unsafe.Pointer(&in.AllowedNodes))
	if err := Convert_v1alpha2_NetworkConfig_To_v1alpha1_NetworkConfig(&in.NetworkConfig, &out.NetworkConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(in *v1alpha2.ProxmoxClusterSpec, out *ProxmoxClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(in *ProxmoxClusterStatus, out *v1alpha2.ProxmoxClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.InClusterIPPoolRef = *(*[]v1.LocalObjectReference)(unsafe.Pointer(&in.InClusterIPPoolRef))
	out.NodeLocations = (*v1alpha2.NodeLocations)(unsafe.Pointer(in.NodeLocations))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(in *ProxmoxClusterStatus, out *v1alpha2.ProxmoxClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(in *v1alpha2.ProxmoxClusterStatus, out *ProxmoxClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.InClusterIPPoolRef = *(*[]v1.LocalObjectReference)(unsafe.Pointer(&in.InClusterIPPoolRef))
	out.NodeLocations = (*NodeLocations)(unsafe.Pointer(in.NodeLocations))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(in *v1alpha2.ProxmoxClusterStatus, out *ProxmoxClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(in *ProxmoxMachine, out *v1alpha2.ProxmoxMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(in *ProxmoxMachine, out *v1alpha2.ProxmoxMachine, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(in *v1alpha2.ProxmoxMachine, out *ProxmoxMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(in *v1alpha2.ProxmoxMachine, out *ProxmoxMachine, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(in *ProxmoxMachineList, out *v1alpha2.ProxmoxMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ProxmoxMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(in *ProxmoxMachineList, out *v1alpha2.ProxmoxMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(in *v1alpha2.ProxmoxMachineList, out *ProxmoxMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(in *v1alpha2.ProxmoxMachineList, out *ProxmoxMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(in *ProxmoxMachineSpec, out *v1alpha2.ProxmoxMachineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(&in.VirtualMachineCloneSpec, &out.VirtualMachineCloneSpec, s); err != nil {
		return err
	}
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VirtualMachineID = (*int64)(unsafe.Pointer(in.VirtualMachineID))
	out.NumSockets = in.NumSockets
	out.NumCores = in.NumCores
	out.MemoryMiB = in.MemoryMiB
	out.Disks = (*v1alpha2.Storage)(unsafe.Pointer(in.Disks))
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(v1alpha2.NetworkSpec)
		if err := Convert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Network = nil
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(in *ProxmoxMachineSpec, out *v1alpha2.ProxmoxMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(in *v1alpha2.ProxmoxMachineSpec, out *ProxmoxMachineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(&in.VirtualMachineCloneSpec, &out.VirtualMachineCloneSpec, s); err != nil {
		return err
	}
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VirtualMachineID = (*int64)(unsafe.Pointer(in.VirtualMachineID))
	out.NumSockets = in.NumSockets
	out.NumCores = in.NumCores
	out.MemoryMiB = in.MemoryMiB
	out.Disks = (*Storage)(unsafe.Pointer(in.Disks))
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkSpec)
		if err := Convert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Network = nil
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(in *v1alpha2.ProxmoxMachineSpec, out *ProxmoxMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(in *ProxmoxMachineStatus, out *v1alpha2.ProxmoxMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1beta1.MachineAddress)(unsafe.Pointer(&in.Addresses))
	out.VMStatus = v1alpha2.VirtualMachineState(in.VMStatus)
	out.BootstrapDataProvided = (*bool)(unsafe.Pointer(in.BootstrapDataProvided))
	out.IPAddresses = *(*map[string]v1alpha2.IPAddress)(unsafe.Pointer(&in.IPAddresses))
	out.Network = *(*[]v1alpha2.NetworkStatus)(unsafe.Pointer(&in.Network))
	out.ProxmoxNode = (*string)(unsafe.Pointer(in.ProxmoxNode))
	out.TaskRef = (*string)(unsafe.Pointer(in.TaskRef))
	out.RetryAfter = in.RetryAfter
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(in *ProxmoxMachineStatus, out *v1alpha2.ProxmoxMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(in *v1alpha2.ProxmoxMachineStatus, out *ProxmoxMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1beta1.MachineAddress)(unsafe.Pointer(&in.Addresses))
	out.VMStatus = VirtualMachineState(in.VMStatus)
	out.BootstrapDataProvided = (*bool)(unsafe.Pointer(in.BootstrapDataProvided))
	out.IPAddresses = *(*map[string]IPAddress)(unsafe.Pointer(&in.IPAddresses))
	out.Network = *(*[]NetworkStatus)(unsafe.Pointer(&in.Network))
	out.ProxmoxNode = (*string)(unsafe.Pointer(in.ProxmoxNode))
	out.TaskRef = (*string)(unsafe.Pointer(in.TaskRef))
	out.RetryAfter = in.RetryAfter
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(in *v1alpha2.ProxmoxMachineStatus, out *ProxmoxMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(in *ProxmoxMachineTemplate, out *v1alpha2.ProxmoxMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(in *ProxmoxMachineTemplate, out *v1alpha2.ProxmoxMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(in *v1alpha2.ProxmoxMachineTemplate, out *ProxmoxMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(in *v1alpha2.ProxmoxMachineTemplate, out *ProxmoxMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(in *ProxmoxMachineTemplateList, out *v1alpha2.ProxmoxMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ProxmoxMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(in *ProxmoxMachineTemplateList, out *v1alpha2.ProxmoxMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(in *v1alpha2.ProxmoxMachineTemplateList, out *ProxmoxMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(in *v1alpha2.ProxmoxMachineTemplateList, out *ProxmoxMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(in *ProxmoxMachineTemplateResource, out *v1alpha2.ProxmoxMachineTemplateResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(in *ProxmoxMachineTemplateResource, out *v1alpha2.ProxmoxMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(in *v1alpha2.ProxmoxMachineTemplateResource, out *ProxmoxMachineTemplateResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(in *v1alpha2.ProxmoxMachineTemplateResource, out *ProxmoxMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(in *ProxmoxMachineTemplateSpec, out *v1alpha2.ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(in *ProxmoxMachineTemplateSpec, out *v1alpha2.ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(in *v1alpha2.ProxmoxMachineTemplateSpec, out *ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(in *v1alpha2.ProxmoxMachineTemplateSpec, out *ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_Storage_To_v1alpha2_Storage(in *Storage, out *v1alpha2.Storage, s conversion.Scope) error {
	out.BootVolume = (*v1alpha2.DiskSize)(unsafe.Pointer(in.BootVolume))
	return nil
}

// Convert_v1alpha1_Storage_To_v1alpha2_Storage is an autogenerated conversion function.
func Convert_v1alpha1_Storage_To_v1alpha2_Storage(in *Storage, out *v1alpha2.Storage, s conversion.Scope) error {
	return autoConvert_v1alpha1_Storage_To_v1alpha2_Storage(in, out, s)
}

func autoConvert_v1alpha2_Storage_To_v1alpha1_Storage(in *v1alpha2.Storage, out *Storage, s conversion.Scope) error {
	out.BootVolume = (*DiskSize)(unsafe.Pointer(in.BootVolume))
	return nil
}

// Convert_v1alpha2_Storage_To_v1alpha1_Storage is an autogenerated conversion function.
func Convert_v1alpha2_Storage_To_v1alpha1_Storage(in *v1alpha2.Storage, out *Storage, s conversion.Scope) error {
	return autoConvert_v1alpha2_Storage_To_v1alpha1_Storage(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(in *VirtualMachine, out *v1alpha2.VirtualMachine, s conversion.Scope) error {
	out.Node = in.Node
	out.Name = in.Name
	out.VMID = in.VMID
	out.State = v1alpha2.VirtualMachineState(in.State)
	out.Network = *(*[]v1alpha2.NetworkStatus)(unsafe.Pointer(&in.Network))
	return nil
}

// Convert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(in *VirtualMachine, out *v1alpha2.VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(in, out, s)
}

func autoConvert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(in *v1alpha2.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	out.Node = in.Node
	out.Name = in.Name
	out.VMID = in.VMID
	out.State = VirtualMachineState(in.State)
	out.Network = *(*[]NetworkStatus)(unsafe.Pointer(&in.Network))
	return nil
}

// Convert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine is an autogenerated conversion function.
func Convert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(in *v1alpha2.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(in *VirtualMachineCloneSpec, out *v1alpha2.VirtualMachineCloneSpec, s conversion.Scope) error {
	out.SourceNode = in.SourceNode
	out.TemplateID = (*int32)(unsafe.Pointer(in.TemplateID))
	out.Description = (*string)(unsafe.Pointer(in.Description))
	out.Format = (*v1alpha2.TargetFileStorageFormat)(unsafe.Pointer(in.Format))
	out.Full = (*bool)(unsafe.Pointer(in.Full))
	out.Pool = (*string)(unsafe.Pointer(in.Pool))
	out.SnapName = (*string)(unsafe.Pointer(in.SnapName))
	out.Storage = (*string)(unsafe.Pointer(in.Storage))
	out.Target = (*string)(unsafe.Pointer(in.Target))
	return nil
}

// Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(in *VirtualMachineCloneSpec, out *v1alpha2.VirtualMachineCloneSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(in, out, s)
}

func autoConvert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(in *v1alpha2.VirtualMachineCloneSpec, out *VirtualMachineCloneSpec, s conversion.Scope) error {
	out.SourceNode = in.SourceNode
	out.TemplateID = (*int32)(unsafe.Pointer(in.TemplateID))
	out.Description = (*string)(unsafe.Pointer(in.Description))
	out.Format = (*TargetFileStorageFormat)(unsafe.Pointer(in.Format))
	out.Full = (*bool)(unsafe.Pointer(in.Full))
	out.Pool = (*string)(unsafe.Pointer(in.Pool))
	out.SnapName = (*string)(unsafe.Pointer(in.SnapName))
	out.Storage = (*string)(unsafe.Pointer(in.Storage))
	out.Target = (*string)(unsafe.Pointer(in.Target))
	return nil
}

// Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec is an autogenerated conversion function.
func Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(in *v1alpha2.VirtualMachineCloneSpec, out *VirtualMachineCloneSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(in, out, s)
}
