//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha2 "github.com/ionos-cloud/cluster-api-provider-proxmox/api/v1alpha2"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1beta1 "sigs.k8s.io/cluster-api/api/core/v1beta1"
	v1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DiskSize)(nil), (*v1alpha2.DiskSize)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(a.(*DiskSize), b.(*v1alpha2.DiskSize), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.DiskSize)(nil), (*DiskSize)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(a.(*v1alpha2.DiskSize), b.(*DiskSize), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPConfigSpec)(nil), (*v1alpha2.IPConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec(a.(*IPConfigSpec), b.(*v1alpha2.IPConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.IPConfigSpec)(nil), (*IPConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec(a.(*v1alpha2.IPConfigSpec), b.(*IPConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InterfaceConfig)(nil), (*v1alpha2.InterfaceConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InterfaceConfig_To_v1alpha2_InterfaceConfig(a.(*InterfaceConfig), b.(*v1alpha2.InterfaceConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetadataSettings)(nil), (*v1alpha2.MetadataSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MetadataSettings_To_v1alpha2_MetadataSettings(a.(*MetadataSettings), b.(*v1alpha2.MetadataSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.MetadataSettings)(nil), (*MetadataSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_MetadataSettings_To_v1alpha1_MetadataSettings(a.(*v1alpha2.MetadataSettings), b.(*MetadataSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkStatus)(nil), (*v1alpha2.NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(a.(*NetworkStatus), b.(*v1alpha2.NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NetworkStatus)(nil), (*NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(a.(*v1alpha2.NetworkStatus), b.(*NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeLocation)(nil), (*v1alpha2.NodeLocation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(a.(*NodeLocation), b.(*v1alpha2.NodeLocation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeLocations)(nil), (*v1alpha2.NodeLocations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(a.(*NodeLocations), b.(*v1alpha2.NodeLocations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NodeLocations)(nil), (*NodeLocations)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(a.(*v1alpha2.NodeLocations), b.(*NodeLocations), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxCluster)(nil), (*v1alpha2.ProxmoxCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(a.(*ProxmoxCluster), b.(*v1alpha2.ProxmoxCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxCluster)(nil), (*ProxmoxCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(a.(*v1alpha2.ProxmoxCluster), b.(*ProxmoxCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterList)(nil), (*v1alpha2.ProxmoxClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(a.(*ProxmoxClusterList), b.(*v1alpha2.ProxmoxClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterList)(nil), (*ProxmoxClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(a.(*v1alpha2.ProxmoxClusterList), b.(*ProxmoxClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterSpec)(nil), (*v1alpha2.ProxmoxClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(a.(*ProxmoxClusterSpec), b.(*v1alpha2.ProxmoxClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterTemplate)(nil), (*v1alpha2.ProxmoxClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate(a.(*ProxmoxClusterTemplate), b.(*v1alpha2.ProxmoxClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterTemplate)(nil), (*ProxmoxClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate(a.(*v1alpha2.ProxmoxClusterTemplate), b.(*ProxmoxClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterTemplateList)(nil), (*v1alpha2.ProxmoxClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterTemplateList_To_v1alpha2_ProxmoxClusterTemplateList(a.(*ProxmoxClusterTemplateList), b.(*v1alpha2.ProxmoxClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterTemplateList)(nil), (*ProxmoxClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterTemplateList_To_v1alpha1_ProxmoxClusterTemplateList(a.(*v1alpha2.ProxmoxClusterTemplateList), b.(*ProxmoxClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxClusterTemplateSpec)(nil), (*v1alpha2.ProxmoxClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec(a.(*ProxmoxClusterTemplateSpec), b.(*v1alpha2.ProxmoxClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxClusterTemplateSpec)(nil), (*ProxmoxClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec(a.(*v1alpha2.ProxmoxClusterTemplateSpec), b.(*ProxmoxClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachine)(nil), (*v1alpha2.ProxmoxMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(a.(*ProxmoxMachine), b.(*v1alpha2.ProxmoxMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachine)(nil), (*ProxmoxMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(a.(*v1alpha2.ProxmoxMachine), b.(*ProxmoxMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineChecks)(nil), (*v1alpha2.ProxmoxMachineChecks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineChecks_To_v1alpha2_ProxmoxMachineChecks(a.(*ProxmoxMachineChecks), b.(*v1alpha2.ProxmoxMachineChecks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineChecks)(nil), (*ProxmoxMachineChecks)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineChecks_To_v1alpha1_ProxmoxMachineChecks(a.(*v1alpha2.ProxmoxMachineChecks), b.(*ProxmoxMachineChecks), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineList)(nil), (*v1alpha2.ProxmoxMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(a.(*ProxmoxMachineList), b.(*v1alpha2.ProxmoxMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineList)(nil), (*ProxmoxMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(a.(*v1alpha2.ProxmoxMachineList), b.(*ProxmoxMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineSpec)(nil), (*v1alpha2.ProxmoxMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(a.(*ProxmoxMachineSpec), b.(*v1alpha2.ProxmoxMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineSpec)(nil), (*ProxmoxMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(a.(*v1alpha2.ProxmoxMachineSpec), b.(*ProxmoxMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineTemplate)(nil), (*v1alpha2.ProxmoxMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(a.(*ProxmoxMachineTemplate), b.(*v1alpha2.ProxmoxMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineTemplate)(nil), (*ProxmoxMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(a.(*v1alpha2.ProxmoxMachineTemplate), b.(*ProxmoxMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineTemplateList)(nil), (*v1alpha2.ProxmoxMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(a.(*ProxmoxMachineTemplateList), b.(*v1alpha2.ProxmoxMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineTemplateList)(nil), (*ProxmoxMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(a.(*v1alpha2.ProxmoxMachineTemplateList), b.(*ProxmoxMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxmoxMachineTemplateSpec)(nil), (*v1alpha2.ProxmoxMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(a.(*ProxmoxMachineTemplateSpec), b.(*v1alpha2.ProxmoxMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ProxmoxMachineTemplateSpec)(nil), (*ProxmoxMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(a.(*v1alpha2.ProxmoxMachineTemplateSpec), b.(*ProxmoxMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Routing)(nil), (*v1alpha2.Routing)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Routing_To_v1alpha2_Routing(a.(*Routing), b.(*v1alpha2.Routing), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Routing)(nil), (*Routing)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Routing_To_v1alpha1_Routing(a.(*v1alpha2.Routing), b.(*Routing), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SchedulerHints)(nil), (*v1alpha2.SchedulerHints)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SchedulerHints_To_v1alpha2_SchedulerHints(a.(*SchedulerHints), b.(*v1alpha2.SchedulerHints), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.SchedulerHints)(nil), (*SchedulerHints)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_SchedulerHints_To_v1alpha1_SchedulerHints(a.(*v1alpha2.SchedulerHints), b.(*SchedulerHints), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Storage)(nil), (*v1alpha2.Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Storage_To_v1alpha2_Storage(a.(*Storage), b.(*v1alpha2.Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Storage)(nil), (*Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Storage_To_v1alpha1_Storage(a.(*v1alpha2.Storage), b.(*Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemplateSelector)(nil), (*v1alpha2.TemplateSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TemplateSelector_To_v1alpha2_TemplateSelector(a.(*TemplateSelector), b.(*v1alpha2.TemplateSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.TemplateSelector)(nil), (*TemplateSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_TemplateSelector_To_v1alpha1_TemplateSelector(a.(*v1alpha2.TemplateSelector), b.(*TemplateSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemplateSource)(nil), (*v1alpha2.TemplateSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TemplateSource_To_v1alpha2_TemplateSource(a.(*TemplateSource), b.(*v1alpha2.TemplateSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.TemplateSource)(nil), (*TemplateSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_TemplateSource_To_v1alpha1_TemplateSource(a.(*v1alpha2.TemplateSource), b.(*TemplateSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VMIDRange)(nil), (*v1alpha2.VMIDRange)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VMIDRange_To_v1alpha2_VMIDRange(a.(*VMIDRange), b.(*v1alpha2.VMIDRange), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VMIDRange)(nil), (*VMIDRange)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VMIDRange_To_v1alpha1_VMIDRange(a.(*v1alpha2.VMIDRange), b.(*VMIDRange), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VRFDevice)(nil), (*v1alpha2.VRFDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VRFDevice_To_v1alpha2_VRFDevice(a.(*VRFDevice), b.(*v1alpha2.VRFDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VRFDevice)(nil), (*VRFDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VRFDevice_To_v1alpha1_VRFDevice(a.(*v1alpha2.VRFDevice), b.(*VRFDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachine)(nil), (*v1alpha2.VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(a.(*VirtualMachine), b.(*v1alpha2.VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VirtualMachine)(nil), (*VirtualMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(a.(*v1alpha2.VirtualMachine), b.(*VirtualMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualMachineCloneSpec)(nil), (*v1alpha2.VirtualMachineCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(a.(*VirtualMachineCloneSpec), b.(*v1alpha2.VirtualMachineCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VirtualMachineCloneSpec)(nil), (*VirtualMachineCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(a.(*v1alpha2.VirtualMachineCloneSpec), b.(*VirtualMachineCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualNetworkDevices)(nil), (*v1alpha2.VirtualNetworkDevices)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices(a.(*VirtualNetworkDevices), b.(*v1alpha2.VirtualNetworkDevices), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.VirtualNetworkDevices)(nil), (*VirtualNetworkDevices)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices(a.(*v1alpha2.VirtualNetworkDevices), b.(*VirtualNetworkDevices), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*[]string)(nil), (*[]v1alpha2.NetName)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Slice_string_To_Slice_v1alpha2_NetName(a.(*[]string), b.(*[]v1alpha2.NetName), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*[]v1alpha2.NetName)(nil), (*[]string)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Slice_v1alpha2_NetName_To_Slice_string(a.(*[]v1alpha2.NetName), b.(*[]string), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*string)(nil), (*v1alpha2.NetName)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_string_To_v1alpha2_NetName(a.(*string), b.(*v1alpha2.NetName), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.Condition)(nil), (*v1beta1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Condition_To_v1beta1_Condition(a.(*v1.Condition), b.(*v1beta1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*NetworkDevice)(nil), (*v1alpha2.NetworkDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(a.(*NetworkDevice), b.(*v1alpha2.NetworkDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*NetworkSpec)(nil), (*v1alpha2.NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(a.(*NetworkSpec), b.(*v1alpha2.NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ProxmoxClusterCloneSpec)(nil), (*v1alpha2.ProxmoxClusterCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterCloneSpec_To_v1alpha2_ProxmoxClusterCloneSpec(a.(*ProxmoxClusterCloneSpec), b.(*v1alpha2.ProxmoxClusterCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ProxmoxClusterStatus)(nil), (*v1alpha2.ProxmoxClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(a.(*ProxmoxClusterStatus), b.(*v1alpha2.ProxmoxClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ProxmoxClusterTemplateResource)(nil), (*v1alpha2.ProxmoxClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxClusterTemplateResource_To_v1alpha2_ProxmoxClusterTemplateResource(a.(*ProxmoxClusterTemplateResource), b.(*v1alpha2.ProxmoxClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ProxmoxMachineStatus)(nil), (*v1alpha2.ProxmoxMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(a.(*ProxmoxMachineStatus), b.(*v1alpha2.ProxmoxMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ProxmoxMachineTemplateResource)(nil), (*v1alpha2.ProxmoxMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(a.(*ProxmoxMachineTemplateResource), b.(*v1alpha2.ProxmoxMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RouteSpec)(nil), (*v1alpha2.RouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RouteSpec_To_v1alpha2_RouteSpec(a.(*RouteSpec), b.(*v1alpha2.RouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*RoutingPolicySpec)(nil), (*v1alpha2.RoutingPolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RoutingPolicySpec_To_v1alpha2_RoutingPolicySpec(a.(*RoutingPolicySpec), b.(*v1alpha2.RoutingPolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.InterfaceConfig)(nil), (*InterfaceConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_InterfaceConfig_To_v1alpha1_InterfaceConfig(a.(*v1alpha2.InterfaceConfig), b.(*InterfaceConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.NetName)(nil), (*string)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetName_To_string(a.(*v1alpha2.NetName), b.(*string), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.NetworkDevice)(nil), (*NetworkDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice(a.(*v1alpha2.NetworkDevice), b.(*NetworkDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.NetworkSpec)(nil), (*NetworkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(a.(*v1alpha2.NetworkSpec), b.(*NetworkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.NodeLocation)(nil), (*NodeLocation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(a.(*v1alpha2.NodeLocation), b.(*NodeLocation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ProxmoxClusterCloneSpec)(nil), (*ProxmoxClusterCloneSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterCloneSpec_To_v1alpha1_ProxmoxClusterCloneSpec(a.(*v1alpha2.ProxmoxClusterCloneSpec), b.(*ProxmoxClusterCloneSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ProxmoxClusterSpec)(nil), (*ProxmoxClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(a.(*v1alpha2.ProxmoxClusterSpec), b.(*ProxmoxClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ProxmoxClusterStatus)(nil), (*ProxmoxClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(a.(*v1alpha2.ProxmoxClusterStatus), b.(*ProxmoxClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ProxmoxClusterTemplateResource)(nil), (*ProxmoxClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxClusterTemplateResource_To_v1alpha1_ProxmoxClusterTemplateResource(a.(*v1alpha2.ProxmoxClusterTemplateResource), b.(*ProxmoxClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ProxmoxMachineStatus)(nil), (*ProxmoxMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(a.(*v1alpha2.ProxmoxMachineStatus), b.(*ProxmoxMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.ProxmoxMachineTemplateResource)(nil), (*ProxmoxMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(a.(*v1alpha2.ProxmoxMachineTemplateResource), b.(*ProxmoxMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.RouteSpec)(nil), (*RouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RouteSpec_To_v1alpha1_RouteSpec(a.(*v1alpha2.RouteSpec), b.(*RouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.RoutingPolicySpec)(nil), (*RoutingPolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_RoutingPolicySpec_To_v1alpha1_RoutingPolicySpec(a.(*v1alpha2.RoutingPolicySpec), b.(*RoutingPolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.Condition)(nil), (*v1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Condition_To_v1_Condition(a.(*v1beta1.Condition), b.(*v1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.ObjectMeta)(nil), (*v1beta2.ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(a.(*v1beta1.ObjectMeta), b.(*v1beta2.ObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.ObjectMeta)(nil), (*v1beta1.ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(a.(*v1beta2.ObjectMeta), b.(*v1beta1.ObjectMeta), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(in *DiskSize, out *v1alpha2.DiskSize, s conversion.Scope) error {
	out.Disk = in.Disk
	out.SizeGB = in.SizeGB
	return nil
}

// Convert_v1alpha1_DiskSize_To_v1alpha2_DiskSize is an autogenerated conversion function.
func Convert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(in *DiskSize, out *v1alpha2.DiskSize, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiskSize_To_v1alpha2_DiskSize(in, out, s)
}

func autoConvert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(in *v1alpha2.DiskSize, out *DiskSize, s conversion.Scope) error {
	out.Disk = in.Disk
	out.SizeGB = in.SizeGB
	return nil
}

// Convert_v1alpha2_DiskSize_To_v1alpha1_DiskSize is an autogenerated conversion function.
func Convert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(in *v1alpha2.DiskSize, out *DiskSize, s conversion.Scope) error {
	return autoConvert_v1alpha2_DiskSize_To_v1alpha1_DiskSize(in, out, s)
}

func autoConvert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec(in *IPConfigSpec, out *v1alpha2.IPConfigSpec, s conversion.Scope) error {
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	out.Prefix = int32(in.Prefix)
	out.Gateway = in.Gateway
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(int32)
		**out = int32(**in)
	} else {
		out.Metric = nil
	}
	return nil
}

// Convert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec(in *IPConfigSpec, out *v1alpha2.IPConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec(in, out, s)
}

func autoConvert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec(in *v1alpha2.IPConfigSpec, out *IPConfigSpec, s conversion.Scope) error {
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	out.Prefix = int(in.Prefix)
	out.Gateway = in.Gateway
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(uint32)
		**out = uint32(**in)
	} else {
		out.Metric = nil
	}
	return nil
}

// Convert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec is an autogenerated conversion function.
func Convert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec(in *v1alpha2.IPConfigSpec, out *IPConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_InterfaceConfig_To_v1alpha2_InterfaceConfig(in *InterfaceConfig, out *v1alpha2.InterfaceConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_Routing_To_v1alpha2_Routing(&in.Routing, &out.Routing, s); err != nil {
		return err
	}
	if in.LinkMTU != nil {
		in, out := &in.LinkMTU, &out.LinkMTU
		*out = new(int32)
		**out = int32(**in)
	} else {
		out.LinkMTU = nil
	}
	return nil
}

// Convert_v1alpha1_InterfaceConfig_To_v1alpha2_InterfaceConfig is an autogenerated conversion function.
func Convert_v1alpha1_InterfaceConfig_To_v1alpha2_InterfaceConfig(in *InterfaceConfig, out *v1alpha2.InterfaceConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InterfaceConfig_To_v1alpha2_InterfaceConfig(in, out, s)
}

func autoConvert_v1alpha2_InterfaceConfig_To_v1alpha1_InterfaceConfig(in *v1alpha2.InterfaceConfig, out *InterfaceConfig, s conversion.Scope) error {
	// WARNING: in.IPPoolRef requires manual conversion: does not exist in peer-type
	// WARNING: in.DNSServers requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha2_Routing_To_v1alpha1_Routing(&in.Routing, &out.Routing, s); err != nil {
		return err
	}
	if in.LinkMTU != nil {
		in, out := &in.LinkMTU, &out.LinkMTU
		*out = new(uint16)
		**out = uint16(**in)
	} else {
		out.LinkMTU = nil
	}
	return nil
}

func autoConvert_v1alpha1_MetadataSettings_To_v1alpha2_MetadataSettings(in *MetadataSettings, out *v1alpha2.MetadataSettings, s conversion.Scope) error {
	if err := v1.Convert_bool_To_Pointer_bool(&in.ProviderIDInjection, &out.ProviderIDInjection, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MetadataSettings_To_v1alpha2_MetadataSettings is an autogenerated conversion function.
func Convert_v1alpha1_MetadataSettings_To_v1alpha2_MetadataSettings(in *MetadataSettings, out *v1alpha2.MetadataSettings, s conversion.Scope) error {
	return autoConvert_v1alpha1_MetadataSettings_To_v1alpha2_MetadataSettings(in, out, s)
}

func autoConvert_v1alpha2_MetadataSettings_To_v1alpha1_MetadataSettings(in *v1alpha2.MetadataSettings, out *MetadataSettings, s conversion.Scope) error {
	if err := v1.Convert_Pointer_bool_To_bool(&in.ProviderIDInjection, &out.ProviderIDInjection, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_MetadataSettings_To_v1alpha1_MetadataSettings is an autogenerated conversion function.
func Convert_v1alpha2_MetadataSettings_To_v1alpha1_MetadataSettings(in *v1alpha2.MetadataSettings, out *MetadataSettings, s conversion.Scope) error {
	return autoConvert_v1alpha2_MetadataSettings_To_v1alpha1_MetadataSettings(in, out, s)
}

func autoConvert_v1alpha1_NetworkDevice_To_v1alpha2_NetworkDevice(in *NetworkDevice, out *v1alpha2.NetworkDevice, s conversion.Scope) error {
	if err := v1.Convert_string_To_Pointer_string(&in.Bridge, &out.Bridge, s); err != nil {
		return err
	}
	out.Model = (*string)(unsafe.Pointer(in.Model))
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int32)
		**out = int32(**in)
	} else {
		out.MTU = nil
	}
	if in.VLAN != nil {
		in, out := &in.VLAN, &out.VLAN
		*out = new(int32)
		**out = int32(**in)
	} else {
		out.VLAN = nil
	}
	// WARNING: in.DNSServers requires manual conversion: does not exist in peer-type
	// WARNING: in.IPPoolConfig requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha2_NetworkDevice_To_v1alpha1_NetworkDevice(in *v1alpha2.NetworkDevice, out *NetworkDevice, s conversion.Scope) error {
	if err := v1.Convert_Pointer_string_To_string(&in.Bridge, &out.Bridge, s); err != nil {
		return err
	}
	// WARNING: in.DefaultIPv4 requires manual conversion: does not exist in peer-type
	// WARNING: in.DefaultIPv6 requires manual conversion: does not exist in peer-type
	out.Model = (*string)(unsafe.Pointer(in.Model))
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(uint16)
		**out = uint16(**in)
	} else {
		out.MTU = nil
	}
	if in.VLAN != nil {
		in, out := &in.VLAN, &out.VLAN
		*out = new(uint16)
		**out = uint16(**in)
	} else {
		out.VLAN = nil
	}
	// WARNING: in.Name requires manual conversion: does not exist in peer-type
	// WARNING: in.InterfaceConfig requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(in *NetworkSpec, out *v1alpha2.NetworkSpec, s conversion.Scope) error {
	// WARNING: in.Default requires manual conversion: does not exist in peer-type
	// WARNING: in.AdditionalDevices requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices(&in.VirtualNetworkDevices, &out.VirtualNetworkDevices, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(in *v1alpha2.NetworkSpec, out *NetworkSpec, s conversion.Scope) error {
	// WARNING: in.Zone requires manual conversion: does not exist in peer-type
	// WARNING: in.NetworkDevices requires manual conversion: does not exist in peer-type
	if err := Convert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices(&in.VirtualNetworkDevices, &out.VirtualNetworkDevices, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(in *NetworkStatus, out *v1alpha2.NetworkStatus, s conversion.Scope) error {
	if err := v1.Convert_bool_To_Pointer_bool(&in.Connected, &out.Connected, s); err != nil {
		return err
	}
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MACAddr = in.MACAddr
	if err := Convert_string_To_v1alpha2_NetName(&in.NetworkName, &out.NetworkName, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(in *NetworkStatus, out *v1alpha2.NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(in *v1alpha2.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	if err := v1.Convert_Pointer_bool_To_bool(&in.Connected, &out.Connected, s); err != nil {
		return err
	}
	out.IPAddrs = *(*[]string)(unsafe.Pointer(&in.IPAddrs))
	out.MACAddr = in.MACAddr
	if err := Convert_v1alpha2_NetName_To_string(&in.NetworkName, &out.NetworkName, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(in *v1alpha2.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(in *NodeLocation, out *v1alpha2.NodeLocation, s conversion.Scope) error {
	out.Machine = in.Machine
	out.Node = in.Node
	return nil
}

// Convert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation is an autogenerated conversion function.
func Convert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(in *NodeLocation, out *v1alpha2.NodeLocation, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(in, out, s)
}

func autoConvert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(in *v1alpha2.NodeLocation, out *NodeLocation, s conversion.Scope) error {
	out.Machine = in.Machine
	out.Node = in.Node
	// WARNING: in.Zone requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(in *NodeLocations, out *v1alpha2.NodeLocations, s conversion.Scope) error {
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = make([]v1alpha2.NodeLocation, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.ControlPlane = nil
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]v1alpha2.NodeLocation, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_NodeLocation_To_v1alpha2_NodeLocation(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Workers = nil
	}
	return nil
}

// Convert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations is an autogenerated conversion function.
func Convert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(in *NodeLocations, out *v1alpha2.NodeLocations, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(in, out, s)
}

func autoConvert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(in *v1alpha2.NodeLocations, out *NodeLocations, s conversion.Scope) error {
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = make([]NodeLocation, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.ControlPlane = nil
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]NodeLocation, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_NodeLocation_To_v1alpha1_NodeLocation(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Workers = nil
	}
	return nil
}

// Convert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations is an autogenerated conversion function.
func Convert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(in *v1alpha2.NodeLocations, out *NodeLocations, s conversion.Scope) error {
	return autoConvert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(in *ProxmoxCluster, out *v1alpha2.ProxmoxCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(in *ProxmoxCluster, out *v1alpha2.ProxmoxCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(in *v1alpha2.ProxmoxCluster, out *ProxmoxCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(in *v1alpha2.ProxmoxCluster, out *ProxmoxCluster, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterCloneSpec_To_v1alpha2_ProxmoxClusterCloneSpec(in *ProxmoxClusterCloneSpec, out *v1alpha2.ProxmoxClusterCloneSpec, s conversion.Scope) error {
	// WARNING: in.ProxmoxMachineSpec requires manual conversion: does not exist in peer-type
	out.SSHAuthorizedKeys = *(*[]string)(unsafe.Pointer(&in.SSHAuthorizedKeys))
	if err := v1.Convert_string_To_Pointer_string(&in.VirtualIPNetworkInterface, &out.VirtualIPNetworkInterface, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_ProxmoxClusterCloneSpec_To_v1alpha1_ProxmoxClusterCloneSpec(in *v1alpha2.ProxmoxClusterCloneSpec, out *ProxmoxClusterCloneSpec, s conversion.Scope) error {
	// WARNING: in.ProxmoxClusterClassSpec requires manual conversion: does not exist in peer-type
	out.SSHAuthorizedKeys = *(*[]string)(unsafe.Pointer(&in.SSHAuthorizedKeys))
	if err := v1.Convert_Pointer_string_To_string(&in.VirtualIPNetworkInterface, &out.VirtualIPNetworkInterface, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(in *ProxmoxClusterList, out *v1alpha2.ProxmoxClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ProxmoxCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ProxmoxCluster_To_v1alpha2_ProxmoxCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(in *ProxmoxClusterList, out *v1alpha2.ProxmoxClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterList_To_v1alpha2_ProxmoxClusterList(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(in *v1alpha2.ProxmoxClusterList, out *ProxmoxClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ProxmoxCluster_To_v1alpha1_ProxmoxCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(in *v1alpha2.ProxmoxClusterList, out *ProxmoxClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterList_To_v1alpha1_ProxmoxClusterList(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(in *ProxmoxClusterSpec, out *v1alpha2.ProxmoxClusterSpec, s conversion.Scope) error {
	out.ControlPlaneEndpoint = (*v1beta2.APIEndpoint)(unsafe.Pointer(in.ControlPlaneEndpoint))
	if err := v1.Convert_bool_To_Pointer_bool(&in.ExternalManagedControlPlane, &out.ExternalManagedControlPlane, s); err != nil {
		return err
	}
	out.AllowedNodes = *(*[]string)(unsafe.Pointer(&in.AllowedNodes))
	if in.SchedulerHints != nil {
		in, out := &in.SchedulerHints, &out.SchedulerHints
		*out = new(v1alpha2.SchedulerHints)
		if err := Convert_v1alpha1_SchedulerHints_To_v1alpha2_SchedulerHints(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.SchedulerHints = nil
	}
	if in.IPv4Config != nil {
		in, out := &in.IPv4Config, &out.IPv4Config
		*out = new(v1alpha2.IPConfigSpec)
		if err := Convert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.IPv4Config = nil
	}
	if in.IPv6Config != nil {
		in, out := &in.IPv6Config, &out.IPv6Config
		*out = new(v1alpha2.IPConfigSpec)
		if err := Convert_v1alpha1_IPConfigSpec_To_v1alpha2_IPConfigSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.IPv6Config = nil
	}
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	if in.CloneSpec != nil {
		in, out := &in.CloneSpec, &out.CloneSpec
		*out = new(v1alpha2.ProxmoxClusterCloneSpec)
		if err := Convert_v1alpha1_ProxmoxClusterCloneSpec_To_v1alpha2_ProxmoxClusterCloneSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.CloneSpec = nil
	}
	out.CredentialsRef = (*corev1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	return nil
}

// Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(in *ProxmoxClusterSpec, out *v1alpha2.ProxmoxClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(in *v1alpha2.ProxmoxClusterSpec, out *ProxmoxClusterSpec, s conversion.Scope) error {
	out.ControlPlaneEndpoint = (*v1beta1.APIEndpoint)(unsafe.Pointer(in.ControlPlaneEndpoint))
	if err := v1.Convert_Pointer_bool_To_bool(&in.ExternalManagedControlPlane, &out.ExternalManagedControlPlane, s); err != nil {
		return err
	}
	out.AllowedNodes = *(*[]string)(unsafe.Pointer(&in.AllowedNodes))
	if in.SchedulerHints != nil {
		in, out := &in.SchedulerHints, &out.SchedulerHints
		*out = new(SchedulerHints)
		if err := Convert_v1alpha2_SchedulerHints_To_v1alpha1_SchedulerHints(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.SchedulerHints = nil
	}
	if in.IPv4Config != nil {
		in, out := &in.IPv4Config, &out.IPv4Config
		*out = new(IPConfigSpec)
		if err := Convert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.IPv4Config = nil
	}
	if in.IPv6Config != nil {
		in, out := &in.IPv6Config, &out.IPv6Config
		*out = new(IPConfigSpec)
		if err := Convert_v1alpha2_IPConfigSpec_To_v1alpha1_IPConfigSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.IPv6Config = nil
	}
	out.DNSServers = *(*[]string)(unsafe.Pointer(&in.DNSServers))
	// WARNING: in.ZoneConfigs requires manual conversion: does not exist in peer-type
	if in.CloneSpec != nil {
		in, out := &in.CloneSpec, &out.CloneSpec
		*out = new(ProxmoxClusterCloneSpec)
		if err := Convert_v1alpha2_ProxmoxClusterCloneSpec_To_v1alpha1_ProxmoxClusterCloneSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.CloneSpec = nil
	}
	out.CredentialsRef = (*corev1.SecretReference)(unsafe.Pointer(in.CredentialsRef))
	return nil
}

func autoConvert_v1alpha1_ProxmoxClusterStatus_To_v1alpha2_ProxmoxClusterStatus(in *ProxmoxClusterStatus, out *v1alpha2.ProxmoxClusterStatus, s conversion.Scope) error {
	if err := v1.Convert_bool_To_Pointer_bool(&in.Ready, &out.Ready, s); err != nil {
		return err
	}
	out.InClusterIPPoolRef = *(*[]corev1.LocalObjectReference)(unsafe.Pointer(&in.InClusterIPPoolRef))
	if in.NodeLocations != nil {
		in, out := &in.NodeLocations, &out.NodeLocations
		*out = new(v1alpha2.NodeLocations)
		if err := Convert_v1alpha1_NodeLocations_To_v1alpha2_NodeLocations(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.NodeLocations = nil
	}
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

func autoConvert_v1alpha2_ProxmoxClusterStatus_To_v1alpha1_ProxmoxClusterStatus(in *v1alpha2.ProxmoxClusterStatus, out *ProxmoxClusterStatus, s conversion.Scope) error {
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta1.Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1beta1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	if err := v1.Convert_Pointer_bool_To_bool(&in.Ready, &out.Ready, s); err != nil {
		return err
	}
	out.InClusterIPPoolRef = *(*[]corev1.LocalObjectReference)(unsafe.Pointer(&in.InClusterIPPoolRef))
	// WARNING: in.InClusterZoneRef requires manual conversion: does not exist in peer-type
	if in.NodeLocations != nil {
		in, out := &in.NodeLocations, &out.NodeLocations
		*out = new(NodeLocations)
		if err := Convert_v1alpha2_NodeLocations_To_v1alpha1_NodeLocations(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.NodeLocations = nil
	}
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

func autoConvert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate(in *ProxmoxClusterTemplate, out *v1alpha2.ProxmoxClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate(in *ProxmoxClusterTemplate, out *v1alpha2.ProxmoxClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate(in *v1alpha2.ProxmoxClusterTemplate, out *ProxmoxClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate(in *v1alpha2.ProxmoxClusterTemplate, out *ProxmoxClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterTemplateList_To_v1alpha2_ProxmoxClusterTemplateList(in *ProxmoxClusterTemplateList, out *v1alpha2.ProxmoxClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ProxmoxClusterTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ProxmoxClusterTemplate_To_v1alpha2_ProxmoxClusterTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ProxmoxClusterTemplateList_To_v1alpha2_ProxmoxClusterTemplateList is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterTemplateList_To_v1alpha2_ProxmoxClusterTemplateList(in *ProxmoxClusterTemplateList, out *v1alpha2.ProxmoxClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterTemplateList_To_v1alpha2_ProxmoxClusterTemplateList(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterTemplateList_To_v1alpha1_ProxmoxClusterTemplateList(in *v1alpha2.ProxmoxClusterTemplateList, out *ProxmoxClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxClusterTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ProxmoxClusterTemplate_To_v1alpha1_ProxmoxClusterTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ProxmoxClusterTemplateList_To_v1alpha1_ProxmoxClusterTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterTemplateList_To_v1alpha1_ProxmoxClusterTemplateList(in *v1alpha2.ProxmoxClusterTemplateList, out *ProxmoxClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterTemplateList_To_v1alpha1_ProxmoxClusterTemplateList(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxClusterTemplateResource_To_v1alpha2_ProxmoxClusterTemplateResource(in *ProxmoxClusterTemplateResource, out *v1alpha2.ProxmoxClusterTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ProxmoxClusterSpec_To_v1alpha2_ProxmoxClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_ProxmoxClusterTemplateResource_To_v1alpha1_ProxmoxClusterTemplateResource(in *v1alpha2.ProxmoxClusterTemplateResource, out *ProxmoxClusterTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ProxmoxClusterSpec_To_v1alpha1_ProxmoxClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec(in *ProxmoxClusterTemplateSpec, out *v1alpha2.ProxmoxClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProxmoxClusterTemplateResource_To_v1alpha2_ProxmoxClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec(in *ProxmoxClusterTemplateSpec, out *v1alpha2.ProxmoxClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxClusterTemplateSpec_To_v1alpha2_ProxmoxClusterTemplateSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec(in *v1alpha2.ProxmoxClusterTemplateSpec, out *ProxmoxClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProxmoxClusterTemplateResource_To_v1alpha1_ProxmoxClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec(in *v1alpha2.ProxmoxClusterTemplateSpec, out *ProxmoxClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxClusterTemplateSpec_To_v1alpha1_ProxmoxClusterTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(in *ProxmoxMachine, out *v1alpha2.ProxmoxMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(in *ProxmoxMachine, out *v1alpha2.ProxmoxMachine, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(in *v1alpha2.ProxmoxMachine, out *ProxmoxMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(in *v1alpha2.ProxmoxMachine, out *ProxmoxMachine, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineChecks_To_v1alpha2_ProxmoxMachineChecks(in *ProxmoxMachineChecks, out *v1alpha2.ProxmoxMachineChecks, s conversion.Scope) error {
	out.SkipCloudInitStatus = (*bool)(unsafe.Pointer(in.SkipCloudInitStatus))
	out.SkipQemuGuestAgent = (*bool)(unsafe.Pointer(in.SkipQemuGuestAgent))
	return nil
}

// Convert_v1alpha1_ProxmoxMachineChecks_To_v1alpha2_ProxmoxMachineChecks is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineChecks_To_v1alpha2_ProxmoxMachineChecks(in *ProxmoxMachineChecks, out *v1alpha2.ProxmoxMachineChecks, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineChecks_To_v1alpha2_ProxmoxMachineChecks(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineChecks_To_v1alpha1_ProxmoxMachineChecks(in *v1alpha2.ProxmoxMachineChecks, out *ProxmoxMachineChecks, s conversion.Scope) error {
	out.SkipCloudInitStatus = (*bool)(unsafe.Pointer(in.SkipCloudInitStatus))
	out.SkipQemuGuestAgent = (*bool)(unsafe.Pointer(in.SkipQemuGuestAgent))
	return nil
}

// Convert_v1alpha2_ProxmoxMachineChecks_To_v1alpha1_ProxmoxMachineChecks is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineChecks_To_v1alpha1_ProxmoxMachineChecks(in *v1alpha2.ProxmoxMachineChecks, out *ProxmoxMachineChecks, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineChecks_To_v1alpha1_ProxmoxMachineChecks(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(in *ProxmoxMachineList, out *v1alpha2.ProxmoxMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ProxmoxMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ProxmoxMachine_To_v1alpha2_ProxmoxMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(in *ProxmoxMachineList, out *v1alpha2.ProxmoxMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineList_To_v1alpha2_ProxmoxMachineList(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(in *v1alpha2.ProxmoxMachineList, out *ProxmoxMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxMachine, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ProxmoxMachine_To_v1alpha1_ProxmoxMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(in *v1alpha2.ProxmoxMachineList, out *ProxmoxMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineList_To_v1alpha1_ProxmoxMachineList(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(in *ProxmoxMachineSpec, out *v1alpha2.ProxmoxMachineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(&in.VirtualMachineCloneSpec, &out.VirtualMachineCloneSpec, s); err != nil {
		return err
	}
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VirtualMachineID = (*int64)(unsafe.Pointer(in.VirtualMachineID))
	if err := v1.Convert_int32_To_Pointer_int32(&in.NumSockets, &out.NumSockets, s); err != nil {
		return err
	}
	if err := v1.Convert_int32_To_Pointer_int32(&in.NumCores, &out.NumCores, s); err != nil {
		return err
	}
	if err := v1.Convert_int32_To_Pointer_int32(&in.MemoryMiB, &out.MemoryMiB, s); err != nil {
		return err
	}
	out.Disks = (*v1alpha2.Storage)(unsafe.Pointer(in.Disks))
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(v1alpha2.NetworkSpec)
		if err := Convert_v1alpha1_NetworkSpec_To_v1alpha2_NetworkSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Network = nil
	}
	out.VMIDRange = (*v1alpha2.VMIDRange)(unsafe.Pointer(in.VMIDRange))
	out.Checks = (*v1alpha2.ProxmoxMachineChecks)(unsafe.Pointer(in.Checks))
	if in.MetadataSettings != nil {
		in, out := &in.MetadataSettings, &out.MetadataSettings
		*out = new(v1alpha2.MetadataSettings)
		if err := Convert_v1alpha1_MetadataSettings_To_v1alpha2_MetadataSettings(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.MetadataSettings = nil
	}
	out.AllowedNodes = *(*[]string)(unsafe.Pointer(&in.AllowedNodes))
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(in *ProxmoxMachineSpec, out *v1alpha2.ProxmoxMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(in *v1alpha2.ProxmoxMachineSpec, out *ProxmoxMachineSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(&in.VirtualMachineCloneSpec, &out.VirtualMachineCloneSpec, s); err != nil {
		return err
	}
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.VirtualMachineID = (*int64)(unsafe.Pointer(in.VirtualMachineID))
	if err := v1.Convert_Pointer_int32_To_int32(&in.NumSockets, &out.NumSockets, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_int32_To_int32(&in.NumCores, &out.NumCores, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_int32_To_int32(&in.MemoryMiB, &out.MemoryMiB, s); err != nil {
		return err
	}
	out.Disks = (*Storage)(unsafe.Pointer(in.Disks))
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkSpec)
		if err := Convert_v1alpha2_NetworkSpec_To_v1alpha1_NetworkSpec(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Network = nil
	}
	out.VMIDRange = (*VMIDRange)(unsafe.Pointer(in.VMIDRange))
	out.Checks = (*ProxmoxMachineChecks)(unsafe.Pointer(in.Checks))
	if in.MetadataSettings != nil {
		in, out := &in.MetadataSettings, &out.MetadataSettings
		*out = new(MetadataSettings)
		if err := Convert_v1alpha2_MetadataSettings_To_v1alpha1_MetadataSettings(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.MetadataSettings = nil
	}
	out.AllowedNodes = *(*[]string)(unsafe.Pointer(&in.AllowedNodes))
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(in *v1alpha2.ProxmoxMachineSpec, out *ProxmoxMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineStatus_To_v1alpha2_ProxmoxMachineStatus(in *ProxmoxMachineStatus, out *v1alpha2.ProxmoxMachineStatus, s conversion.Scope) error {
	if err := v1.Convert_bool_To_Pointer_bool(&in.Ready, &out.Ready, s); err != nil {
		return err
	}
	out.Addresses = *(*[]v1beta2.MachineAddress)(unsafe.Pointer(&in.Addresses))
	// WARNING: in.VMStatus requires manual conversion: inconvertible types (github.com/ionos-cloud/cluster-api-provider-proxmox/api/v1alpha1.VirtualMachineState vs *github.com/ionos-cloud/cluster-api-provider-proxmox/api/v1alpha2.VirtualMachineState)
	out.BootstrapDataProvided = (*bool)(unsafe.Pointer(in.BootstrapDataProvided))
	// WARNING: in.IPAddresses requires manual conversion: inconvertible types (map[string]github.com/ionos-cloud/cluster-api-provider-proxmox/api/v1alpha1.IPAddress vs []github.com/ionos-cloud/cluster-api-provider-proxmox/api/v1alpha2.IPAddressesSpec)
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = make([]v1alpha2.NetworkStatus, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Network = nil
	}
	out.ProxmoxNode = (*string)(unsafe.Pointer(in.ProxmoxNode))
	out.TaskRef = (*string)(unsafe.Pointer(in.TaskRef))
	// WARNING: in.RetryAfter requires manual conversion: inconvertible types (k8s.io/apimachinery/pkg/apis/meta/v1.Time vs *k8s.io/apimachinery/pkg/apis/meta/v1.Time)
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_Condition_To_v1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	return nil
}

func autoConvert_v1alpha2_ProxmoxMachineStatus_To_v1alpha1_ProxmoxMachineStatus(in *v1alpha2.ProxmoxMachineStatus, out *ProxmoxMachineStatus, s conversion.Scope) error {
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta1.Conditions, len(*in))
		for i := range *in {
			if err := Convert_v1_Condition_To_v1beta1_Condition(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Conditions = nil
	}
	if err := v1.Convert_Pointer_bool_To_bool(&in.Ready, &out.Ready, s); err != nil {
		return err
	}
	out.Addresses = *(*[]v1beta1.MachineAddress)(unsafe.Pointer(&in.Addresses))
	// WARNING: in.VMStatus requires manual conversion: inconvertible types (*github.com/ionos-cloud/cluster-api-provider-proxmox/api/v1alpha2.VirtualMachineState vs github.com/ionos-cloud/cluster-api-provider-proxmox/api/v1alpha1.VirtualMachineState)
	out.BootstrapDataProvided = (*bool)(unsafe.Pointer(in.BootstrapDataProvided))
	// WARNING: in.IPAddresses requires manual conversion: inconvertible types ([]github.com/ionos-cloud/cluster-api-provider-proxmox/api/v1alpha2.IPAddressesSpec vs map[string]github.com/ionos-cloud/cluster-api-provider-proxmox/api/v1alpha1.IPAddress)
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = make([]NetworkStatus, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Network = nil
	}
	out.ProxmoxNode = (*string)(unsafe.Pointer(in.ProxmoxNode))
	out.TaskRef = (*string)(unsafe.Pointer(in.TaskRef))
	// WARNING: in.RetryAfter requires manual conversion: inconvertible types (*k8s.io/apimachinery/pkg/apis/meta/v1.Time vs k8s.io/apimachinery/pkg/apis/meta/v1.Time)
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

func autoConvert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(in *ProxmoxMachineTemplate, out *v1alpha2.ProxmoxMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(in *ProxmoxMachineTemplate, out *v1alpha2.ProxmoxMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(in *v1alpha2.ProxmoxMachineTemplate, out *ProxmoxMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(in *v1alpha2.ProxmoxMachineTemplate, out *ProxmoxMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(in *ProxmoxMachineTemplateList, out *v1alpha2.ProxmoxMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.ProxmoxMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ProxmoxMachineTemplate_To_v1alpha2_ProxmoxMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(in *ProxmoxMachineTemplateList, out *v1alpha2.ProxmoxMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineTemplateList_To_v1alpha2_ProxmoxMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(in *v1alpha2.ProxmoxMachineTemplateList, out *ProxmoxMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxMachineTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_ProxmoxMachineTemplate_To_v1alpha1_ProxmoxMachineTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(in *v1alpha2.ProxmoxMachineTemplateList, out *ProxmoxMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineTemplateList_To_v1alpha1_ProxmoxMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(in *ProxmoxMachineTemplateResource, out *v1alpha2.ProxmoxMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ProxmoxMachineSpec_To_v1alpha2_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(in *v1alpha2.ProxmoxMachineTemplateResource, out *ProxmoxMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_ProxmoxMachineSpec_To_v1alpha1_ProxmoxMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(in *ProxmoxMachineTemplateSpec, out *v1alpha2.ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ProxmoxMachineTemplateResource_To_v1alpha2_ProxmoxMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(in *ProxmoxMachineTemplateSpec, out *v1alpha2.ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProxmoxMachineTemplateSpec_To_v1alpha2_ProxmoxMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(in *v1alpha2.ProxmoxMachineTemplateSpec, out *ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_ProxmoxMachineTemplateResource_To_v1alpha1_ProxmoxMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(in *v1alpha2.ProxmoxMachineTemplateSpec, out *ProxmoxMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_ProxmoxMachineTemplateSpec_To_v1alpha1_ProxmoxMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_RouteSpec_To_v1alpha2_RouteSpec(in *RouteSpec, out *v1alpha2.RouteSpec, s conversion.Scope) error {
	if err := v1.Convert_string_To_Pointer_string(&in.To, &out.To, s); err != nil {
		return err
	}
	if err := v1.Convert_string_To_Pointer_string(&in.Via, &out.Via, s); err != nil {
		return err
	}
	// WARNING: in.Metric requires manual conversion: inconvertible types (uint32 vs *int32)
	// WARNING: in.Table requires manual conversion: inconvertible types (uint32 vs *int32)
	return nil
}

func autoConvert_v1alpha2_RouteSpec_To_v1alpha1_RouteSpec(in *v1alpha2.RouteSpec, out *RouteSpec, s conversion.Scope) error {
	if err := v1.Convert_Pointer_string_To_string(&in.To, &out.To, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_string_To_string(&in.Via, &out.Via, s); err != nil {
		return err
	}
	// WARNING: in.Metric requires manual conversion: inconvertible types (*int32 vs uint32)
	// WARNING: in.Table requires manual conversion: inconvertible types (*int32 vs uint32)
	return nil
}

func autoConvert_v1alpha1_Routing_To_v1alpha2_Routing(in *Routing, out *v1alpha2.Routing, s conversion.Scope) error {
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]v1alpha2.RouteSpec, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_RouteSpec_To_v1alpha2_RouteSpec(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Routes = nil
	}
	if in.RoutingPolicy != nil {
		in, out := &in.RoutingPolicy, &out.RoutingPolicy
		*out = make([]v1alpha2.RoutingPolicySpec, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_RoutingPolicySpec_To_v1alpha2_RoutingPolicySpec(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.RoutingPolicy = nil
	}
	return nil
}

// Convert_v1alpha1_Routing_To_v1alpha2_Routing is an autogenerated conversion function.
func Convert_v1alpha1_Routing_To_v1alpha2_Routing(in *Routing, out *v1alpha2.Routing, s conversion.Scope) error {
	return autoConvert_v1alpha1_Routing_To_v1alpha2_Routing(in, out, s)
}

func autoConvert_v1alpha2_Routing_To_v1alpha1_Routing(in *v1alpha2.Routing, out *Routing, s conversion.Scope) error {
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]RouteSpec, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_RouteSpec_To_v1alpha1_RouteSpec(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Routes = nil
	}
	if in.RoutingPolicy != nil {
		in, out := &in.RoutingPolicy, &out.RoutingPolicy
		*out = make([]RoutingPolicySpec, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_RoutingPolicySpec_To_v1alpha1_RoutingPolicySpec(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.RoutingPolicy = nil
	}
	return nil
}

// Convert_v1alpha2_Routing_To_v1alpha1_Routing is an autogenerated conversion function.
func Convert_v1alpha2_Routing_To_v1alpha1_Routing(in *v1alpha2.Routing, out *Routing, s conversion.Scope) error {
	return autoConvert_v1alpha2_Routing_To_v1alpha1_Routing(in, out, s)
}

func autoConvert_v1alpha1_RoutingPolicySpec_To_v1alpha2_RoutingPolicySpec(in *RoutingPolicySpec, out *v1alpha2.RoutingPolicySpec, s conversion.Scope) error {
	if err := v1.Convert_string_To_Pointer_string(&in.To, &out.To, s); err != nil {
		return err
	}
	if err := v1.Convert_string_To_Pointer_string(&in.From, &out.From, s); err != nil {
		return err
	}
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(int32)
		**out = int32(**in)
	} else {
		out.Table = nil
	}
	// WARNING: in.Priority requires manual conversion: inconvertible types (uint32 vs *int64)
	return nil
}

func autoConvert_v1alpha2_RoutingPolicySpec_To_v1alpha1_RoutingPolicySpec(in *v1alpha2.RoutingPolicySpec, out *RoutingPolicySpec, s conversion.Scope) error {
	if err := v1.Convert_Pointer_string_To_string(&in.To, &out.To, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_string_To_string(&in.From, &out.From, s); err != nil {
		return err
	}
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(uint32)
		**out = uint32(**in)
	} else {
		out.Table = nil
	}
	// WARNING: in.Priority requires manual conversion: inconvertible types (*int64 vs uint32)
	return nil
}

func autoConvert_v1alpha1_SchedulerHints_To_v1alpha2_SchedulerHints(in *SchedulerHints, out *v1alpha2.SchedulerHints, s conversion.Scope) error {
	if in.MemoryAdjustment != nil {
		in, out := &in.MemoryAdjustment, &out.MemoryAdjustment
		*out = new(int64)
		**out = int64(**in)
	} else {
		out.MemoryAdjustment = nil
	}
	return nil
}

// Convert_v1alpha1_SchedulerHints_To_v1alpha2_SchedulerHints is an autogenerated conversion function.
func Convert_v1alpha1_SchedulerHints_To_v1alpha2_SchedulerHints(in *SchedulerHints, out *v1alpha2.SchedulerHints, s conversion.Scope) error {
	return autoConvert_v1alpha1_SchedulerHints_To_v1alpha2_SchedulerHints(in, out, s)
}

func autoConvert_v1alpha2_SchedulerHints_To_v1alpha1_SchedulerHints(in *v1alpha2.SchedulerHints, out *SchedulerHints, s conversion.Scope) error {
	if in.MemoryAdjustment != nil {
		in, out := &in.MemoryAdjustment, &out.MemoryAdjustment
		*out = new(uint64)
		**out = uint64(**in)
	} else {
		out.MemoryAdjustment = nil
	}
	return nil
}

// Convert_v1alpha2_SchedulerHints_To_v1alpha1_SchedulerHints is an autogenerated conversion function.
func Convert_v1alpha2_SchedulerHints_To_v1alpha1_SchedulerHints(in *v1alpha2.SchedulerHints, out *SchedulerHints, s conversion.Scope) error {
	return autoConvert_v1alpha2_SchedulerHints_To_v1alpha1_SchedulerHints(in, out, s)
}

func autoConvert_v1alpha1_Storage_To_v1alpha2_Storage(in *Storage, out *v1alpha2.Storage, s conversion.Scope) error {
	out.BootVolume = (*v1alpha2.DiskSize)(unsafe.Pointer(in.BootVolume))
	return nil
}

// Convert_v1alpha1_Storage_To_v1alpha2_Storage is an autogenerated conversion function.
func Convert_v1alpha1_Storage_To_v1alpha2_Storage(in *Storage, out *v1alpha2.Storage, s conversion.Scope) error {
	return autoConvert_v1alpha1_Storage_To_v1alpha2_Storage(in, out, s)
}

func autoConvert_v1alpha2_Storage_To_v1alpha1_Storage(in *v1alpha2.Storage, out *Storage, s conversion.Scope) error {
	out.BootVolume = (*DiskSize)(unsafe.Pointer(in.BootVolume))
	return nil
}

// Convert_v1alpha2_Storage_To_v1alpha1_Storage is an autogenerated conversion function.
func Convert_v1alpha2_Storage_To_v1alpha1_Storage(in *v1alpha2.Storage, out *Storage, s conversion.Scope) error {
	return autoConvert_v1alpha2_Storage_To_v1alpha1_Storage(in, out, s)
}

func autoConvert_v1alpha1_TemplateSelector_To_v1alpha2_TemplateSelector(in *TemplateSelector, out *v1alpha2.TemplateSelector, s conversion.Scope) error {
	out.MatchTags = *(*[]string)(unsafe.Pointer(&in.MatchTags))
	return nil
}

// Convert_v1alpha1_TemplateSelector_To_v1alpha2_TemplateSelector is an autogenerated conversion function.
func Convert_v1alpha1_TemplateSelector_To_v1alpha2_TemplateSelector(in *TemplateSelector, out *v1alpha2.TemplateSelector, s conversion.Scope) error {
	return autoConvert_v1alpha1_TemplateSelector_To_v1alpha2_TemplateSelector(in, out, s)
}

func autoConvert_v1alpha2_TemplateSelector_To_v1alpha1_TemplateSelector(in *v1alpha2.TemplateSelector, out *TemplateSelector, s conversion.Scope) error {
	out.MatchTags = *(*[]string)(unsafe.Pointer(&in.MatchTags))
	return nil
}

// Convert_v1alpha2_TemplateSelector_To_v1alpha1_TemplateSelector is an autogenerated conversion function.
func Convert_v1alpha2_TemplateSelector_To_v1alpha1_TemplateSelector(in *v1alpha2.TemplateSelector, out *TemplateSelector, s conversion.Scope) error {
	return autoConvert_v1alpha2_TemplateSelector_To_v1alpha1_TemplateSelector(in, out, s)
}

func autoConvert_v1alpha1_TemplateSource_To_v1alpha2_TemplateSource(in *TemplateSource, out *v1alpha2.TemplateSource, s conversion.Scope) error {
	if err := v1.Convert_string_To_Pointer_string(&in.SourceNode, &out.SourceNode, s); err != nil {
		return err
	}
	out.TemplateID = (*int32)(unsafe.Pointer(in.TemplateID))
	out.TemplateSelector = (*v1alpha2.TemplateSelector)(unsafe.Pointer(in.TemplateSelector))
	return nil
}

// Convert_v1alpha1_TemplateSource_To_v1alpha2_TemplateSource is an autogenerated conversion function.
func Convert_v1alpha1_TemplateSource_To_v1alpha2_TemplateSource(in *TemplateSource, out *v1alpha2.TemplateSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_TemplateSource_To_v1alpha2_TemplateSource(in, out, s)
}

func autoConvert_v1alpha2_TemplateSource_To_v1alpha1_TemplateSource(in *v1alpha2.TemplateSource, out *TemplateSource, s conversion.Scope) error {
	if err := v1.Convert_Pointer_string_To_string(&in.SourceNode, &out.SourceNode, s); err != nil {
		return err
	}
	out.TemplateID = (*int32)(unsafe.Pointer(in.TemplateID))
	out.TemplateSelector = (*TemplateSelector)(unsafe.Pointer(in.TemplateSelector))
	return nil
}

// Convert_v1alpha2_TemplateSource_To_v1alpha1_TemplateSource is an autogenerated conversion function.
func Convert_v1alpha2_TemplateSource_To_v1alpha1_TemplateSource(in *v1alpha2.TemplateSource, out *TemplateSource, s conversion.Scope) error {
	return autoConvert_v1alpha2_TemplateSource_To_v1alpha1_TemplateSource(in, out, s)
}

func autoConvert_v1alpha1_VMIDRange_To_v1alpha2_VMIDRange(in *VMIDRange, out *v1alpha2.VMIDRange, s conversion.Scope) error {
	out.Start = in.Start
	out.End = in.End
	return nil
}

// Convert_v1alpha1_VMIDRange_To_v1alpha2_VMIDRange is an autogenerated conversion function.
func Convert_v1alpha1_VMIDRange_To_v1alpha2_VMIDRange(in *VMIDRange, out *v1alpha2.VMIDRange, s conversion.Scope) error {
	return autoConvert_v1alpha1_VMIDRange_To_v1alpha2_VMIDRange(in, out, s)
}

func autoConvert_v1alpha2_VMIDRange_To_v1alpha1_VMIDRange(in *v1alpha2.VMIDRange, out *VMIDRange, s conversion.Scope) error {
	out.Start = in.Start
	out.End = in.End
	return nil
}

// Convert_v1alpha2_VMIDRange_To_v1alpha1_VMIDRange is an autogenerated conversion function.
func Convert_v1alpha2_VMIDRange_To_v1alpha1_VMIDRange(in *v1alpha2.VMIDRange, out *VMIDRange, s conversion.Scope) error {
	return autoConvert_v1alpha2_VMIDRange_To_v1alpha1_VMIDRange(in, out, s)
}

func autoConvert_v1alpha1_VRFDevice_To_v1alpha2_VRFDevice(in *VRFDevice, out *v1alpha2.VRFDevice, s conversion.Scope) error {
	if err := Convert_Slice_string_To_Slice_v1alpha2_NetName(&in.Interfaces, &out.Interfaces, s); err != nil {
		return err
	}
	out.Name = in.Name
	out.Table = int32(in.Table)
	if err := Convert_v1alpha1_Routing_To_v1alpha2_Routing(&in.Routing, &out.Routing, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VRFDevice_To_v1alpha2_VRFDevice is an autogenerated conversion function.
func Convert_v1alpha1_VRFDevice_To_v1alpha2_VRFDevice(in *VRFDevice, out *v1alpha2.VRFDevice, s conversion.Scope) error {
	return autoConvert_v1alpha1_VRFDevice_To_v1alpha2_VRFDevice(in, out, s)
}

func autoConvert_v1alpha2_VRFDevice_To_v1alpha1_VRFDevice(in *v1alpha2.VRFDevice, out *VRFDevice, s conversion.Scope) error {
	if err := Convert_Slice_v1alpha2_NetName_To_Slice_string(&in.Interfaces, &out.Interfaces, s); err != nil {
		return err
	}
	out.Name = in.Name
	out.Table = uint32(in.Table)
	if err := Convert_v1alpha2_Routing_To_v1alpha1_Routing(&in.Routing, &out.Routing, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_VRFDevice_To_v1alpha1_VRFDevice is an autogenerated conversion function.
func Convert_v1alpha2_VRFDevice_To_v1alpha1_VRFDevice(in *v1alpha2.VRFDevice, out *VRFDevice, s conversion.Scope) error {
	return autoConvert_v1alpha2_VRFDevice_To_v1alpha1_VRFDevice(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(in *VirtualMachine, out *v1alpha2.VirtualMachine, s conversion.Scope) error {
	out.Node = in.Node
	out.Name = in.Name
	out.VMID = int64(in.VMID)
	out.State = v1alpha2.VirtualMachineState(in.State)
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = make([]v1alpha2.NetworkStatus, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_NetworkStatus_To_v1alpha2_NetworkStatus(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Network = nil
	}
	return nil
}

// Convert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(in *VirtualMachine, out *v1alpha2.VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachine_To_v1alpha2_VirtualMachine(in, out, s)
}

func autoConvert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(in *v1alpha2.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	out.Node = in.Node
	out.Name = in.Name
	out.VMID = uint64(in.VMID)
	out.State = VirtualMachineState(in.State)
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = make([]NetworkStatus, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_NetworkStatus_To_v1alpha1_NetworkStatus(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Network = nil
	}
	return nil
}

// Convert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine is an autogenerated conversion function.
func Convert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(in *v1alpha2.VirtualMachine, out *VirtualMachine, s conversion.Scope) error {
	return autoConvert_v1alpha2_VirtualMachine_To_v1alpha1_VirtualMachine(in, out, s)
}

func autoConvert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(in *VirtualMachineCloneSpec, out *v1alpha2.VirtualMachineCloneSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_TemplateSource_To_v1alpha2_TemplateSource(&in.TemplateSource, &out.TemplateSource, s); err != nil {
		return err
	}
	out.Description = (*string)(unsafe.Pointer(in.Description))
	out.Format = (*v1alpha2.TargetFileStorageFormat)(unsafe.Pointer(in.Format))
	out.Full = (*bool)(unsafe.Pointer(in.Full))
	out.Pool = (*string)(unsafe.Pointer(in.Pool))
	out.SnapName = (*string)(unsafe.Pointer(in.SnapName))
	out.Storage = (*string)(unsafe.Pointer(in.Storage))
	out.Target = (*string)(unsafe.Pointer(in.Target))
	return nil
}

// Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(in *VirtualMachineCloneSpec, out *v1alpha2.VirtualMachineCloneSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualMachineCloneSpec_To_v1alpha2_VirtualMachineCloneSpec(in, out, s)
}

func autoConvert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(in *v1alpha2.VirtualMachineCloneSpec, out *VirtualMachineCloneSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_TemplateSource_To_v1alpha1_TemplateSource(&in.TemplateSource, &out.TemplateSource, s); err != nil {
		return err
	}
	out.Description = (*string)(unsafe.Pointer(in.Description))
	out.Format = (*TargetFileStorageFormat)(unsafe.Pointer(in.Format))
	out.Full = (*bool)(unsafe.Pointer(in.Full))
	out.Pool = (*string)(unsafe.Pointer(in.Pool))
	out.SnapName = (*string)(unsafe.Pointer(in.SnapName))
	out.Storage = (*string)(unsafe.Pointer(in.Storage))
	out.Target = (*string)(unsafe.Pointer(in.Target))
	return nil
}

// Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec is an autogenerated conversion function.
func Convert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(in *v1alpha2.VirtualMachineCloneSpec, out *VirtualMachineCloneSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_VirtualMachineCloneSpec_To_v1alpha1_VirtualMachineCloneSpec(in, out, s)
}

func autoConvert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices(in *VirtualNetworkDevices, out *v1alpha2.VirtualNetworkDevices, s conversion.Scope) error {
	if in.VRFs != nil {
		in, out := &in.VRFs, &out.VRFs
		*out = make([]v1alpha2.VRFDevice, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_VRFDevice_To_v1alpha2_VRFDevice(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.VRFs = nil
	}
	return nil
}

// Convert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices is an autogenerated conversion function.
func Convert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices(in *VirtualNetworkDevices, out *v1alpha2.VirtualNetworkDevices, s conversion.Scope) error {
	return autoConvert_v1alpha1_VirtualNetworkDevices_To_v1alpha2_VirtualNetworkDevices(in, out, s)
}

func autoConvert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices(in *v1alpha2.VirtualNetworkDevices, out *VirtualNetworkDevices, s conversion.Scope) error {
	if in.VRFs != nil {
		in, out := &in.VRFs, &out.VRFs
		*out = make([]VRFDevice, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_VRFDevice_To_v1alpha1_VRFDevice(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.VRFs = nil
	}
	return nil
}

// Convert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices is an autogenerated conversion function.
func Convert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices(in *v1alpha2.VirtualNetworkDevices, out *VirtualNetworkDevices, s conversion.Scope) error {
	return autoConvert_v1alpha2_VirtualNetworkDevices_To_v1alpha1_VirtualNetworkDevices(in, out, s)
}
