---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/proxmox-cluster-cni: cilium
  name: capmox-cluster
spec:
  topology:
    class: proxmox-clusterclass-cilium-v0.1.0
    version: 1.25.10
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
      - class: proxmox-worker
        name: proxmox-worker-pool
        replicas: 3
    variables:
    - name: allowedNodes
      value:
      - pve1
      - pve2
      - pve3
    - name: controlPlaneEndpoint
      value:
        host: 10.10.10.9
        port: 6443
    - name: dnsServers
      value: [8.8.8.8, 8.8.4.4]
    - name: ipv4Config
      value:
        addresses: [10.10.10.10-10.10.10.20]
        gateway: 10.10.10.1
        prefix: 24
#   - name: ipv6Config
#     value:
#       addresses: [2001:db8:1::10-2001:db8:1::20]
#       gateway: 2001:db8:1::1
#       prefix: 64
    - name: nodeCloneSpec
      value:
#       network:
#         default:
#           bridge: vmbr0
#         additionalDevices:
#           - name: net1
#             model: virtio
#             ipv4PoolRef:
#               name: shared-inclusteripv4pool
#               apiGroup: ipam.cluster.x-k8s.io
#               kind: GlobalInClusterIPPool
#             ipv6PoolRef:
#               name: shared-inclusteripv6pool
#               apiGroup: ipam.cluster.x-k8s.io
#               kind: GlobalInClusterIPPool
#             bridge: vmbr1
#       numSockets: 1
#       numCores: 2
#       memoryMiB: 2048
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJPK5kBd7cxXAHZ6UbeE+ysOlSjOFare3fCCZJ3xtXt1 capmox@k8s.io
        sourceNode: pve1
        templateID: 100
#       virtualIPNetworkInterface: eno1
# ---
# apiVersion: ipam.cluster.x-k8s.io/v1alpha2
# kind: GlobalInClusterIPPool
# metadata:
#   name: shared-inclusteripv4pool
# spec:
#   addresses:
#   - 10.10.11.1
#   - 10.10.11.2
#   - 10.10.11.3
#   prefix: 24
#   gateway: 10.10.11.254
# ---
# apiVersion: ipam.cluster.x-k8s.io/v1alpha2
# kind: GlobalInClusterIPPool
# metadata:
#   name: shared-inclusteripv6pool
# spec:
#   addresses:
#   - 2001:db8::10
#   - 2001:db8::11
#   - 2001:db8::12
#   prefix: 64
#   gateway: 2001:db8::1
