name: Comment

on:
  pull_request_target:
    types: ["opened"]
    branches: ["main"]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ### Tests
            Please note that running unit and e2e tests requires manual approval from a team member.
            
            ### e2e tests
            We use labels to control which e2e tests contexts are run:
            
            | Label | Behaviour |
            |--|--|
            | none | Run `Generic` tests only |
            | https://github.com/ionos-cloud/cluster-api-provider-proxmox/labels/e2e%2Fnone | Do not run any e2e tests |
            | https://github.com/ionos-cloud/cluster-api-provider-proxmox/labels/e2e%2Fflatcar | Add `Flatcar` tests |
            
            ℹ️ Ask a team member to add the requested labels if you don't have enough permissions.
          comment_tag: comment
          mode: "recreate"
