name: "e2e (main/PR)"

on:
  push:
    branches: [main]
  pull_request:
    types: ["opened", "synchronize", "reopened", "labeled", "unlabeled"]

jobs:
  e2e:
    if: >-
      github.event_name == 'push' ||
      (github.event.pull_request.user.login != 'dependabot[bot]' &&
       !github.event.pull_request.head.repo.fork &&
       !contains(github.event.pull_request.labels.*.name, 'e2e/none'))
    uses: ./.github/workflows/e2e.yml
