name: Test external PR
on:
  push:
    branches: ["main"]
  pull_request_target:
    branches: ["main"]

jobs:
  go_test:
    if: ${{ github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-latest
    environment: e2e # request confirmation
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0 # for sonarcloud
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: "make verify"
      - run: "make test"
      - uses: SonarSource/sonarcloud-github-action@v4.0.0
        with:
         args: >
           -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
           -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
